version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x
  
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - go mod download
      
  build:
    commands:
      - echo "Building Lambda function..."
      - GOOS=linux GOARCH=amd64 go build -o main
      
  post_build:
    commands:
      - echo "Creating deployment package..."
      - zip function.zip main
      - aws lambda update-function-code --function-name ALSCalendarParser --zip-file fileb://function.zip --publish
      - |
        # Get current version from LIVE alias if it exists
        CURRENT_VERSION=$(aws lambda get-alias --function-name ALSCalendarParser --name LIVE --query 'FunctionVersion' --output text 2>/dev/null || echo "\$LATEST")
        LATEST_VERSION=$(aws lambda list-versions-by-function --function-name ALSCalendarParser --query 'Versions[-1].Version' --output text)
        
        # Update appspec.yml with correct versions
        sed -i.bak "s/\$CURRENT_VERSION/$CURRENT_VERSION/" appspec.yml
        sed -i.bak "s/\$LATEST/$LATEST_VERSION/" appspec.yml
        
        # Create or update LIVE alias
        if ! aws lambda get-alias --function-name ALSCalendarParser --name LIVE &> /dev/null; then
          aws lambda create-alias --function-name ALSCalendarParser --name LIVE --function-version $LATEST_VERSION
        else
          aws lambda update-alias --function-name ALSCalendarParser --name LIVE --function-version $LATEST_VERSION
        fi

artifacts:
  files:
    - appspec.yml
    - function.zip
  discard-paths: yes

cache:
  paths:
    - /go/pkg/mod/**/* 